# Generated by Django 4.2 on 2023-12-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0002_alter_musteri_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 8, 33, 17, 947529), editable=False),
        ),
    ]
