# Generated by Django 4.2 on 2023-12-24 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun_siparis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunsiparis',
            old_name='siparis_id',
            new_name='siparis',
        ),
        migrations.RenameField(
            model_name='urunsiparis',
            old_name='urun_id',
            new_name='urun',
        ),
        migrations.AlterField(
            model_name='urunsiparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 8, 25, 25, 126122), editable=False),
        ),
    ]
