# Generated by Django 4.2 on 2023-12-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun_siparis', '0002_rename_siparis_id_urunsiparis_siparis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunsiparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 8, 33, 17, 948308), editable=False),
        ),
    ]
