# Generated by Django 4.2 on 2024-01-13 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun_siparis', '0005_alter_urunsiparis_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunsiparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 8, 45, 6, 486631), editable=False),
        ),
    ]
