# Generated by Django 4.2 on 2024-01-14 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun_siparis', '0008_alter_urunsiparis_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunsiparis',
            name='siparis_durumu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urunsiparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 9, 46, 21, 867507), editable=False),
        ),
    ]
