# Generated by Django 4.2 on 2023-12-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0003_alter_urun_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 9, 34, 45, 28129), editable=False),
        ),
    ]
