# Generated by Django 4.2 on 2023-12-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0002_alter_siparis_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siparis',
            old_name='adres_id',
            new_name='adres',
        ),
        migrations.RenameField(
            model_name='siparis',
            old_name='musteri_id',
            new_name='musteri',
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 8, 33, 17, 947875), editable=False),
        ),
    ]
