# Generated by Django 4.2 on 2024-01-13 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0006_alter_siparis_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 8, 59, 16, 657467), editable=False),
        ),
    ]
