# Generated by Django 4.2 on 2024-01-14 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0007_alter_siparis_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 9, 32, 28, 315889), editable=False),
        ),
    ]
