# Generated by Django 4.2 on 2023-12-24 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 8, 25, 25, 125462), editable=False),
        ),
    ]
