# Generated by Django 4.2 on 2023-12-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adres', '0003_rename_musteri_id_adres_musteri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 9, 34, 45, 27478), editable=False),
        ),
    ]
