# Generated by Django 4.2 on 2024-01-14 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adres', '0008_alter_adres_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 9, 46, 21, 866462), editable=False),
        ),
    ]
